name = "Dojo"
uuid = "ac60b53e-8d92-4c83-b960-e78698fa1916"
authors = ["simonlc <simonlc@stanford.edu>", "thowell <thowell@stanford.edu>", "Jan Bruedigam <jan.bruedigam@tum.de>"]
version = "0.7.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GraphBasedSystems = "c7b9bcad-ccd7-4721-b0c6-1499c55cf356"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Colors = "<0.12.10, 0.12.10"
CoordinateTransformations = "<0.6.3, 0.6.3"
DocStringExtensions = "<0.9.3, 0.9.3"
FFMPEG = "0.4.0, 0.4.1"
FiniteDiff = "2.0, 2.21"
GeometryBasics = "<0.4.7, 0.4.7"
GraphBasedSystems = "1.0, 1.2"
LaTeXStrings = "1.3, 1.3"
LightXML = "<0.9.0, 0.9.0"
MeshCat = "<0.16.0, 0.16.0"
Meshing = "<0.6.0, 0.6.0"
Polyhedra = "<0.7.6, 0.7.6"
Quaternions = "0.5.2, 0.7.0, 0.7.4"
StaticArrays = "1.2, 1.5"
julia = "1.6, 1.9"
