name = "Dojo"
uuid = "ac60b53e-8d92-4c83-b960-e78698fa1916"
authors = ["simonlc <simonlc@stanford.edu>", "thowell <thowell@stanford.edu>", "Jan Bruedigam <jan.bruedigam@tum.de>"]
version = "0.3.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Colors = "<0.12.8, 0.12.8"
CoordinateTransformations = "<0.6.2, 0.6.2"
DocStringExtensions = "<0.8.6, 0.8.6"
FFMPEG = "0.4.0, 0.4.1"
FiniteDiff = "2.0, 2.11"
GeometryBasics = "<0.4.2, 0.4.2"
Graphs = "1.5, 1.6"
JLD2 = "<0.4.22, 0.4.22"
LaTeXStrings = "1.3, 1.3"
LightXML = "<0.9.0, 0.9.0"
MeshCat = "<0.14.2, 0.14.2"
Meshing = "<0.5.7, 0.5.7"
Parameters = "<0.12.3, 0.12.3"
Polyhedra = "<0.7.5, 0.7.5"
Quaternions = "0.5.2, 0.5.6"
Scratch = "1.1, 1.1"
StaticArrays = "1.2, 1.4"
julia = "1.6, 1.7"
