name = "DojoEnvironments"
uuid = "8728bab7-e8ae-46fd-a1b6-a8c4d00f608e"
authors = ["simonlc <simonlc@stanford.edu>", "thowell <thowell@stanford.edu>", "Jan Bruedigam <jan.bruedigam@tum.de>", "rejuvyesh <mail@rejuvyesh.com>"]
version = "0.2.1"

[deps]
Dojo = "ac60b53e-8d92-4c83-b960-e78698fa1916"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Dojo = "0.3.0, 0.4.0, 0.5.0"
MeshCat = "<0.14.2, 0.14.2"
StaticArrays = "1.2, 1.5"
julia = "1.6, 1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
