[deps]
IterativeLQR = "605048dd-e178-462b-beb9-98a09398ef27"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PGFPlots = "3b7a836e-365b-5785-a47d-02c71176b4aa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
IterativeLQR = "0.1.1"
Literate = "2.13.0"
Plots = "1.25.11"
PGFPlots = "3.4.1"
