[deps]
Dojo = "ac60b53e-8d92-4c83-b960-e78698fa1916"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IterativeLQR = "605048dd-e178-462b-beb9-98a09398ef27"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PGFPlots = "3b7a836e-365b-5785-a47d-02c71176b4aa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
FiniteDiff = "2.11.0"
Folds = "0.2"
JLD2 = "0.4.21"
Literate = "2.13.0"
PGFPlots = "3.4.1"
Plots = "1.25.11"
